CREATE TABLE `test`.`TORIHIKISAKI_MAIN` (
                                            `TORIHIKI_ID` INT(11) NOT NULL,
                                            `TORIHIKI_NAME_ALL` VARCHAR(50) NOT NULL,
                                            `TORIHIKI_NAME_RYAKU` VARCHAR(30) NOT NULL,
                                            `YUUBIN` CHAR(8) NOT NULL,
                                            `JYUSYO_1` VARCHAR(100) NOT NULL,
                                            `JYUSYO_2` VARCHAR(100) NULL,
                                            `TEL` VARCHAR(15) NULL,
                                            `FAX` VARCHAR(15) NULL,
                                            `URL` VARCHAR(100) NULL,
                                            `BIKOU` VARCHAR(255) NULL,
                                            `DELETE_FLAG` INT(11) NOT NULL,
                                            `SEIKYUSYO_KUBUN_1` INT(11) NULL,
                                            `SEIKYUSYO_KUBUN_2` INT(11) NULL,
                                            `SEIKYUSYO_KUBUN_3` INT(11) NULL,
                                            `SEIKYUSYO_KUBUN_4` INT(11) NULL,
                                            `SEIKYUSYO_KUBUN_5` INT(11) NULL,
                                            `SEIKYUSYO_KUBUN_6` INT(11) NULL,
                                            `SEIKYUSYO_KUBUN_7` VARCHAR(255) NULL,
                                            `SEIKYUSYO_KUBUN_8` VARCHAR(255) NULL,
                                            `SEIKYUSYO_KUBUN_9` VARCHAR(255) NULL,
                                            `SEIKYUSYO_KUBUN_10` VARCHAR(255) NULL,
                                            `SEIKYUSYO_KUBUN_11` VARCHAR(255) NULL,
                                            `HONSYA` INT(11) NULL,
                                            `HONSYA_KOUZA` INT(11) NULL,
                                            `KINYUKIKAN_CODE` VARCHAR(10) NULL,
                                            `KINYUKIKAN_NAME` VARCHAR(50) NULL,
                                            `SITEN_CODE` VARCHAR(10) NULL,
                                            `SITEN_NAME` VARCHAR(50) NULL,
                                            `KOUZA_KIND` INT NULL,
                                            `KOUZA_NUM` VARCHAR(10) NULL,
                                            `MEIGI_NAME` VARCHAR(50) NULL,
                                            `TOUROKUBI` DATETIME NULL,
                                            `KOUSINNBI` DATETIME NULL,
                                            PRIMARY KEY (`TORIHIKI_ID`));
